CC = gcc -Wall -std=c11 -ggdb
MERGE_4_SMALL = create_table 4                                    \
	merge_files                                                   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \

MERGE_4_MEDIUM = create_table 4                                     \
	merge_files                                                     \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \

MERGE_4_LARGE = create_table 4                                    \
	merge_files                                                   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \

MERGE_10_SMALL = create_table 10                                  \
	merge_files                                                   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \

MERGE_10_MEDIUM = create_table 10                                   \
	merge_files                                                     \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \

MERGE_10_LARGE = create_table 10                                  \
	merge_files                                                   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \


MERGE_20_SMALL = create_table 20                                  \
	merge_files                                                   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \
		test_text_files/small_a.txt:test_text_files/small_b.txt   \

MERGE_20_MEDIUM = create_table 20                                   \
	merge_files                                                     \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \
		test_text_files/medium_a.txt:test_text_files/medium_b.txt   \

MERGE_20_LARGE = create_table 20                                  \
	merge_files                                                   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \
		test_text_files/large_a.txt:test_text_files/large_b.txt   \

run:
	@$(CC) main.c -o main.o -L. -lmerge_shared
	@LD_LIBRARY_PATH="." ./main.o $(MERGE_4_LARGE)

all: run

clean:
	rm *.o temp_merge_file.txt

